# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely edit after that. If you find
# yourself editing this file very often, consider using Jekyll's data files
# feature for the data you need to update frequently.
#
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'bundle exec jekyll serve'. If you change this file, please restart the server process.

# Site settings
# These are used to personalize your new site. If you look in the HTML files,
# you will see them accessed via {{ site.title }}, {{ site.email }}, and so on.
# You can create any custom variable you would like, and they will be accessible
# in the templates via {{ site.myvariable }}.
title: 安藤 拓翔 (ANDO takuto)のプロフィール
email:
description: >- # this means to ignore newlines until "baseurl:"
  大分高専の安藤 拓翔です。研究活動やプロフィールについて紹介します。
twitter_username: username
github_username: username
minimal_mistakes_skin: default
search: true

# Build settings
markdown: kramdown
remote_theme: mmistakes/minimal-mistakes
# Outputting
permalink: /:categories/:title/
paginate: 5 # amount of posts to show
paginate_path: /page:num/
timezone: Asia/Tokyo

kramdown:
  parse_block_html: true


include:
  - _pages

# Exclude from processing.
# The following items will not be processed, by default. Create a custom list
# to override the default setting.
# exclude:
#   - Gemfile
#   - Gemfile.lock
#   - node_modules
#   - vendor/bundle/
#   - vendor/cache/
#   - vendor/gems/
#   - vendor/ruby/

# Plugins (previously gems:)
plugins:
  - jekyll-paginate
  - jekyll-sitemap
  - jekyll-gist
  - jekyll-feed
  - jemoji
  - jekyll-include-cache
  - jekyll-sitemap
  - jekyll-polyglot

author:
  name   : "安藤 拓翔 (ANDO takuto)"
  avatar : "/assets/images/bio.png"
  bio    : "大分工業高等専門学校 専攻科 
            電気電子情報工学専攻 2年"
  location: "Oita"
  links:
    - label: "researchmap"
      icon: "fas fa-fw fa-link"
      url: "https://researchmap.jp/takuto_ando"
    - label: "GitHub"
      icon: "fab fa-fw fa-github"
      url: "https://github.com/Takuto-Ando"



footer:
  links:
    - label: "GitHub"
      icon: "fab fa-fw fa-github"
      url: "https://github.com/Takuto-Ando"
    - label: "researchmap"
      icon: "fas fa-fw fa-link"
      url: "https://researchmap.jp/takuto_ando"



defaults:
  # _posts
  - scope:
      path: ""
      type: posts
    values:
      layout: single
      author_profile: true
      read_time: true
      comments: true
      share: true
      related: true
  # _pages
  - scope:
      path: "_pages"
      type: pages
    values:
      layout: single
      author_profile: true
      

potfolio:
  type: liquid
  path: /categories/
tag_archive:
  type: liquid
  path: /tags/


google_analytics: GT-WRF24CXG

languages: ['ja', 'ko', 'en']
default_lang: 'ja'
exclude_from_localization: ['javascript', 'images', 'css']
parallel_localization: false
locale: "ja" 
site.locale: "ja-JP"